package upbit;

public enum CoinSymbol
{
	BTC, ADA, EOS, TRX, STORM, IGNIS, XRP, GTO, XLM,
	SC, ETH, SNT, QTUM, BCC, NEO, SBD, ETC, ARDR, GRS,
	XMR, STEEM, GNT, ICX, LSK, XEM, POWR, MER, EMC2,
	STRAT, OMG, LTC, TIX, BTG, PIVX, MCO, WAVES, STORJ,
	DASH, KMD, VTC, MTL, REP, ARK, ZEC
}
